server:
  port: 8901
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #配置存储配置信息的Git仓库
          uri: https://gitee.com/sixsixsix516/SpringCloudConfigDemo.git
          username: 13289333516
          password: shenxian516
          clone-on-start: true #开启启动时直接从git获取配置
          search-paths: "test"
eureka:
  client:
    service-url:
      defaultZone: http://sixsixsix516:123456@localhost:8001/eureka/

management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'
