server:
  port: 8202
spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://sixsixsix516:123456@localhost:8001/eureka/
